version: "0.1"
user: amitwalia
key: GLuoOMYYMQ4t3T41p9CtUQiVZ9xqjGboG2imkQzliz407avzue
testSuites: []
pre: [npm install]
runson: win
autosplit: true
concurrency: 10
testDiscovery:
  command: grep -lr 'describe' tests/specs/demo_vd.js
  mode: static
  type: raw
testDiscoveryResult:
- tests/specs/demo_vd.js
testRunnerCommand: npx wdio conf\wdio.conf.js --spec tests\specs\demo_vd.js
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
cacheDirectories:
- .node_modules
cacheKey: '{{ checksum "package-lock.json" }}'
jobID: be53f856-b33e-49a8-a1ee-d9363f9055ba
codeDirectory: WebdriverIO-HyperExecute-Sample
